// <auto-generated />
using System;
using AlumniTrackingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SlsuAlumniApi.Migrations
{
    [DbContext(typeof(AlumniDbContext))]
    [Migration("20260427094346_AddExamResults")]
    partial class AddExamResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AlumniTrackingAPI.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Super Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$RRg1ix7KqCO/rr.tbJR12eiTqeUZIEp5r4cgInJSmRuN1juYp5Ssq",
                            Role = "superadmin",
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("AlumniTrackingAPI.Models.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DifferenceFromNational")
                        .HasColumnType("REAL");

                    b.Property<int>("FirstTimeExaminees")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstTimePassers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FirstTimePassingRate")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationalExaminees")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NationalPassers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("NationalPassingRate")
                        .HasColumnType("REAL");

                    b.Property<int>("RepeaterExaminees")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeaterPassers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RepeaterPassingRate")
                        .HasColumnType("REAL");

                    b.Property<int>("SlsuExaminees")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlsuPassers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SlsuPassingRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("AlumniTrackingAPI.Models.PendingSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Awards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraduateSchoolProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthTaken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassedLicensureExam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasserStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PresentAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearEnrolled")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearGraduated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YearTaken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PendingSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
